### ISSUE TITLE
please remove older build for 3.1.2

### ISSUE THREAD

**Issue by doutriaux1** [conda-forge/cdms2-feedstock#30]
Conda solver picks lower unsatisfactory builds please remove all build number lesser than 7 for version 3.1.2

Thanks.

**Comment by doutriaux1** [comment]
@ocefpaf sorry to bother you on this, but we do not have permission to remove/change channel.

Thanks. For more details on this issue see: https://github.com/conda/conda/issues/8333

**Comment by ocefpaf** [comment]
> @ocefpaf sorry to bother you on this, but we do not have permission to remove/change channel.

No problem in pinging me directly but, for Anaconda channel issues like those, you can ping @conda-forge/core and probably a quicker answer from anyone listening (including myself).

Can you check if I got it right:

https://anaconda.org/conda-forge/cdms2/files?version=3.1.2

**Comment by doutriaux1** [comment]
that did it. Thx!
